# Generated by Django 3.0.2 on 2022-01-30 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'ok'), ('REPAIRING', 'repairing'), ('UNAVAILABLE', 'unavaliable')], max_length=32)),
                ('last_check', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
