# Generated by Django 3.0.2 on 2022-01-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0002_bike_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bstations', '0002_bstation_maintainer'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='bike_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ticket', to='bikes.Bike'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='station_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ticket', to='bstations.BStation'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='ticket_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_ticket', to='tickets.Ticket'),
        ),
    ]
