# Generated by Django 3.0.2 on 2022-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lat', models.DecimalField(decimal_places=32, max_digits=32)),
                ('lon', models.DecimalField(decimal_places=32, max_digits=32)),
                ('image', models.CharField(max_length=255)),
                ('nslots', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
