# Generated by Django 3.0.2 on 2022-01-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bstation',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
